### ISSUE TITLE
Modify Highlights of GitHub Campus Expert

### ISSUE THREAD

**Issue by gomzyakov** [github-profile-achievements/chinese#10]
Like in https://github.com/github-profile-achievements/english/pull/36

**Comment by ZJamss** [comment]
I think this issue should be closed because the content has expired.

**Comment by gomzyakov** [comment]
@ZJamss Thanks for the note! Closing the issue.

**Comment by shaoting0730** [comment]
❤️❤️❤️

**Comment by chuanye-Wang** [comment]
❤️
